name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: final_test
      id: final_test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FINAL_TEST_RESULTS: "${{steps.final_test.outputs.result}}"
      with:
        runners: final_test
